== Requirements for Attendees

To make the most out of the "Getting Started with Service Mesh" workshop, attendees are expected to meet the following requirements:

. *Basic knowledge of application development*:
Attendees should be familiar with any modern programming language (Java, kotlin, JavaScript, Python). 
Some of the demo applications will be using Java and Kotlin. 
But Service Mesh concepts can be translated to any language.

. *Familiarity with containerization*:
A basic understanding of Docker and containerization concepts is essential, as the workshop will involve deploying applications within containers.

. *Experience with Kubernetes*:
Attendees should have a working knowledge of Kubernetes, including concepts like clusters, nodes, deployments, and services.
Prior experience using Minikube for local Kubernetes development is strongly recommended.

. *Understanding of service mesh concepts*:
A basic understanding of service mesh architecture and its benefits will help attendees grasp the workshop material more effectively.
Prior knowledge of service mesh technologies (Istio, Kuma, Linkerd, etc.) is a plus but optional, as attendees will receive an introduction to the service mesh pattern during the workshop.

. *Pre-installed software and tools*:
Ensure that the following tools are installed and set up on your local machine before attending the workshop:
- link:https://www.docker.com/products/docker-desktop[Docker (latest version)]
- link:https://minikube.sigs.k8s.io/docs/start/[Minikube (latest version)]
- link:https://kubernetes.io/docs/tasks/tools/install-kubectl/[Kubectl (latest version)]
- link:https://k9scli.io/topics/install/[K9s Kubernetes client (latest version)]
- link:http://https://insomnia.rest/download[Insomnia]

. *Laptop with an appropriate operating system*:
Attendees should bring a laptop with a Linux or macOS operating system, at least 8 GB of RAM, and a modern multicore processor to run the necessary tools and applications during the workshop.
Ensure that you have a stable internet connection for the workshop's duration.

NOTE: For Windows laptop users, unfortunately, we don't have access to Windows machines to validate all the instructions.
If you bring a Windows laptop, ensure you have appropriate rights to install software like Docker or Minikube.
Please be aware that the workshop experience might not be as seamless as using a Linux or macOS operating system.

. *Active participation*:
Attendees are expected to actively engage in hands-on exercises and discussions throughout the workshop to maximize learning and gain practical experience with service mesh technologies.

NOTE: Grafana and Prometheus will be installed during the workshop, so there is no need to pre-install them on your local machine.

By meeting these requirements, attendees will be well-prepared to participate in the "Getting Started with Service Mesh" workshop,
enhancing their understanding of service mesh technologies and their benefits for application developers.

<<top, Back on top☝️>>