#meet:
#  server:
#    url: http://localhost:8080/
micronaut:
  application:
    name: work
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  routes:
    enabled: true
    sensitive: false
  health:
    enabled: true