apiVersion: kuma.io/v1alpha1
kind: FaultInjection
mesh: default
metadata:
  name: fail-50-percent
spec:
  sources:
    - match:
        kuma.io/service: "work_mesh4devs_svc_8081"
        kuma.io/protocol: http
  destinations:
    - match:
        kuma.io/service: "meeting_mesh4devs_svc_8080"
        kuma.io/protocol: http
  conf:
    abort:
      httpStatus: 500
      percentage: 50
    responseBandwidth:
      limit: 50 mbps
      percentage: 50 
